// ─── DONNÉES ET CONSTANTES DU MODULE REPORTS ─────────────────────
// Contient : TABLE_CATALOG, DASHBOARD_CATALOG, computeKPIs,
//            TEMPLATE_DEFAULTS, QUICK_TEMPLATES, uid, filterConditionalBlocks
import { Block } from '../../engine/reportBlocks';
import { fmtMoney } from '../../lib/format';

export const TABLE_CATALOG: Array<{ v: string; label: string; cat: string; desc: string }> = [
  { v: 'bilan_actif', label: 'Bilan — Actif', cat: 'États', desc: 'Actif immobilisé, circulant, trésorerie' },
  { v: 'bilan_passif', label: 'Bilan — Passif', cat: 'États', desc: 'Capitaux propres, ressources stables, dettes' },
  { v: 'cr', label: 'Compte de résultat', cat: 'États', desc: 'CR officiel SYSCOHADA avec SIG' },
  { v: 'sig', label: 'Soldes intermédiaires (SIG)', cat: 'États', desc: 'Marge brute, VA, EBE, RE, RN' },
  { v: 'balance', label: 'Balance générale', cat: 'États', desc: 'Tous les comptes mouvementés' },
  { v: 'tft', label: 'Tableau des flux de trésorerie', cat: 'États', desc: 'CAFG, BFR, flux op./inv./fin.' },
  { v: 'capital', label: 'Variation des capitaux propres', cat: 'États', desc: 'Mouvements par rubrique' },
  // ─── États financiers pro IFRS (niveau GT : comparatif N/N-1 + réf. normatives) ───
  { v: 'ifrs_pnl', label: 'IFRS — Compte de résultat', cat: 'IFRS', desc: 'P&L IAS 1 par nature · N/N-1 · réf. normatives' },
  { v: 'ifrs_oci', label: 'IFRS — Résultat global (OCI)', cat: 'IFRS', desc: 'Other comprehensive income IAS 1.82A' },
  { v: 'ifrs_sofp', label: 'IFRS — Situation financière', cat: 'IFRS', desc: 'SoFP current/non-current · N/N-1 · réf. IAS' },
  { v: 'ifrs_sce', label: 'IFRS — Variation des capitaux propres', cat: 'IFRS', desc: 'Statement of changes in equity IAS 1.106' },
  { v: 'ifrs_cashflow', label: 'IFRS — Flux de trésorerie', cat: 'IFRS', desc: 'IAS 7 méthode indirecte · réf. normatives' },
  { v: 'ifrs_recon', label: 'IFRS — Réconciliation SYSCOHADA→IFRS', cat: 'IFRS', desc: 'Ponts capitaux propres & résultat (IFRS 1)' },
  { v: 'ratios', label: 'Ratios financiers', cat: 'Analyse', desc: 'Rentabilité, liquidité, structure, activité' },
  { v: 'budget_actual', label: 'Budget vs Réalisé (annuel)', cat: 'Analyse', desc: 'Écarts annuels par compte sur tout le CR' },
  { v: 'cr_monthly', label: 'CR mensuel (Jan→Déc)', cat: 'Mensuel', desc: 'Compte de résultat mois par mois' },
  { v: 'bilan_monthly', label: 'Bilan mensuel (Jan→Déc)', cat: 'Mensuel', desc: 'Bilan actif/passif mois par mois' },
  { v: 'budget_monthly', label: 'Budget vs Réalisé (mensuel + N-1)', cat: 'Mensuel', desc: 'Réalisé / Budget / N-1 par mois et par section' },
  // ─── CR Bloc Tables : Monthly ───
  { v: 'crtab_produits_expl_m', label: "Produits expl. — Monthly", cat: 'CR Monthly', desc: '70-75 : Actual / Budget / N-1 mois + YTD' },
  { v: 'crtab_charges_expl_m', label: "Charges expl. — Monthly", cat: 'CR Monthly', desc: '60-66 : Actual / Budget / N-1 mois + YTD' },
  { v: 'crtab_produits_fin_m', label: 'Produits fin. — Monthly', cat: 'CR Monthly', desc: '77 : Actual / Budget / N-1 mois + YTD' },
  { v: 'crtab_charges_fin_m', label: 'Charges fin. — Monthly', cat: 'CR Monthly', desc: '67 : Actual / Budget / N-1 mois + YTD' },
  { v: 'crtab_produits_hao_m', label: 'Produits HAO — Monthly', cat: 'CR Monthly', desc: '82,84,86,88 : Actual / Budget / N-1 mois + YTD' },
  { v: 'crtab_charges_hao_m', label: 'Charges HAO — Monthly', cat: 'CR Monthly', desc: '81,83,85 : Actual / Budget / N-1 mois + YTD' },
  { v: 'crtab_impots_m', label: 'Impôts — Monthly', cat: 'CR Monthly', desc: '87,89 : Actual / Budget / N-1 mois + YTD' },
  // ─── CR Bloc Tables : Quarterly ───
  { v: 'crtab_produits_expl_q', label: "Produits expl. — Quarterly", cat: 'CR Quarterly', desc: '70-75 : Actual / Budget / N-1 trimestre + YTD' },
  { v: 'crtab_charges_expl_q', label: "Charges expl. — Quarterly", cat: 'CR Quarterly', desc: '60-66 : Actual / Budget / N-1 trimestre + YTD' },
  { v: 'crtab_produits_fin_q', label: 'Produits fin. — Quarterly', cat: 'CR Quarterly', desc: '77 : Actual / Budget / N-1 trimestre + YTD' },
  { v: 'crtab_charges_fin_q', label: 'Charges fin. — Quarterly', cat: 'CR Quarterly', desc: '67 : Actual / Budget / N-1 trimestre + YTD' },
  { v: 'crtab_impots_q', label: 'Impôts — Quarterly', cat: 'CR Quarterly', desc: '87,89 : Actual / Budget / N-1 trimestre + YTD' },
  // ─── CR Bloc Tables : Interim (S1/S2) ───
  { v: 'crtab_produits_expl_s', label: "Produits expl. — Interim", cat: 'CR Interim', desc: '70-75 : Actual / Budget / N-1 semestre + YTD' },
  { v: 'crtab_charges_expl_s', label: "Charges expl. — Interim", cat: 'CR Interim', desc: '60-66 : Actual / Budget / N-1 semestre + YTD' },
  { v: 'crtab_produits_fin_s', label: 'Produits fin. — Interim', cat: 'CR Interim', desc: '77 : Actual / Budget / N-1 semestre + YTD' },
  { v: 'crtab_charges_fin_s', label: 'Charges fin. — Interim', cat: 'CR Interim', desc: '67 : Actual / Budget / N-1 semestre + YTD' },
  { v: 'crtab_impots_s', label: 'Impôts — Interim', cat: 'CR Interim', desc: '87,89 : Actual / Budget / N-1 semestre + YTD' },
  // ─── CR Bloc Tables : Annual ───
  { v: 'crtab_produits_expl_a', label: "Produits expl. — Annual", cat: 'CR Annual', desc: '70-75 : Actual / Budget / N-1 exercice complet' },
  { v: 'crtab_charges_expl_a', label: "Charges expl. — Annual", cat: 'CR Annual', desc: '60-66 : Actual / Budget / N-1 exercice complet' },
  { v: 'crtab_produits_fin_a', label: 'Produits fin. — Annual', cat: 'CR Annual', desc: '77 : Actual / Budget / N-1 exercice complet' },
  { v: 'crtab_charges_fin_a', label: 'Charges fin. — Annual', cat: 'CR Annual', desc: '67 : Actual / Budget / N-1 exercice complet' },
  { v: 'crtab_impots_a', label: 'Impôts — Annual', cat: 'CR Annual', desc: '87,89 : Actual / Budget / N-1 exercice complet' },
];

// Synchronisé avec le catalogue Dashboards
export const DASHBOARD_CATALOG: Array<{ id: string; name: string; cat: string; desc: string }> = [
  // ─── Dashboards Premium ★ ───
  { id: 'struct_actif', name: 'Structure de l\'Actif ★', cat: 'Premium', desc: 'Donut + table : immo / circulant / trésorerie' },
  { id: 'struct_passif', name: 'Structure du Passif ★', cat: 'Premium', desc: 'Donut + table : CP / dettes financières / circulantes' },
  { id: 'pyramide_perf', name: 'Pyramide des performances ★', cat: 'Premium', desc: 'ROE = Marge × Rotation × Levier (analyse Du Pont)' },
  { id: 'ratios_table', name: 'Table des Ratios financiers ★', cat: 'Premium', desc: 'Tous ratios + cibles + statut + benchmark' },
  { id: 'exec', name: 'Executive Summary ★', cat: 'Premium', desc: 'Vue exécutive : KPIs, radar, cascade SIG, alertes' },
  { id: 'compliance', name: 'Compliance SYSCOHADA ★', cat: 'Premium', desc: '10 contrôles automatiques de conformité' },
  { id: 'breakeven', name: 'Seuil de rentabilité ★', cat: 'Premium', desc: 'Point mort, marge de sécurité, coûts fixes/variables' },
  { id: 'pareto', name: 'Analyse ABC (Pareto) ★', cat: 'Premium', desc: 'Top 20% des comptes qui font 80% du CA / charges' },
  { id: 'cashforecast', name: 'Cashflow prévisionnel 13 sem ★', cat: 'Premium', desc: 'Projection 13 semaines + alertes' },
  { id: 'waterfall', name: 'Waterfall — Cascade SIG ★', cat: 'Premium', desc: 'Cascade visuelle CA → Résultat Net' },
  // ─── Standards ───
  { id: 'home', name: 'Synthèse de gestion', cat: 'Standard', desc: "KPIs, alertes, structure financière" },
  { id: 'cp', name: 'Charges & Produits', cat: 'Standard', desc: 'Répartition par nature, top 10' },
  { id: 'crblock', name: 'CR par bloc', cat: 'Standard', desc: '7 sections + résultats intermédiaires' },
  { id: 'client', name: 'Cycle Client', cat: 'Standard', desc: 'DSO, balance âgée, top débiteurs' },
  { id: 'fr', name: 'Cycle Fournisseur', cat: 'Standard', desc: 'DPO, échéancier, concentration' },
  { id: 'stk', name: 'Stocks', cat: 'Standard', desc: 'Valorisation, dépréciations, rotation' },
  { id: 'immo', name: 'Immobilisations', cat: 'Standard', desc: 'VNC, amortissements, vétusté' },
  { id: 'tre', name: 'Trésorerie', cat: 'Standard', desc: 'Position, flux, volatilité' },
  { id: 'bfr', name: 'BFR', cat: 'Standard', desc: 'FR, BFR, TN, équation' },
  { id: 'sal', name: 'Masse salariale', cat: 'Standard', desc: 'Charges, ratio, évolution' },
  { id: 'fis', name: 'Fiscalité', cat: 'Standard', desc: 'TVA, IS, pression fiscale' },
  { id: 'is_bvsa', name: 'Budget vs Actual (annuel)', cat: 'Reporting', desc: 'Réalisé vs Budget annuel par section' },
  { id: 'is_bvsa_monthly', name: 'Budget vs Actual (mensuel + N-1)', cat: 'Reporting', desc: 'Comparaison mensuelle Réalisé / Budget / N-1' },
  { id: 'cashflow', name: 'Cashflow Statement', cat: 'Reporting', desc: 'KPIs + Cash In/Out + Solde' },
  { id: 'receivables', name: 'Receivables & Payables Review', cat: 'Reporting', desc: 'Donuts + évolution mensuelle' },
  { id: 'crsec_produits_expl', name: "CR — Produits d'exploitation", cat: 'CR détaillé', desc: 'Comptes 70-75' },
  { id: 'crsec_charges_expl', name: "CR — Charges d'exploitation", cat: 'CR détaillé', desc: 'Comptes 60-66' },
  { id: 'crsec_produits_fin', name: 'CR — Produits financiers', cat: 'CR détaillé', desc: 'Comptes 77' },
  { id: 'crsec_charges_fin', name: 'CR — Charges financières', cat: 'CR détaillé', desc: 'Comptes 67' },
  { id: 'crsec_produits_hao', name: 'CR — Produits exceptionnels', cat: 'CR détaillé', desc: 'Comptes 82, 84, 86, 88' },
  { id: 'crsec_charges_hao', name: 'CR — Charges exceptionnelles', cat: 'CR détaillé', desc: 'Comptes 81, 83, 85' },
  { id: 'crsec_impots', name: 'CR — Impôts sur bénéfices', cat: 'CR détaillé', desc: 'Comptes 87, 89' },
  // CR Bloc Dashboards par période
  { id: 'crblock_monthly', name: 'CR Bloc — Monthly', cat: 'CR Monthly', desc: 'Toutes sections CR : Actual/Budget/N-1 mois + YTD' },
  { id: 'crblock_quarterly', name: 'CR Bloc — Quarterly', cat: 'CR Quarterly', desc: 'Toutes sections CR : trimestre + YTD' },
  { id: 'crblock_interim', name: 'CR Bloc — Interim', cat: 'CR Interim', desc: 'Toutes sections CR : semestre + YTD' },
  { id: 'crblock_annual', name: 'CR Bloc — Annual', cat: 'CR Annual', desc: 'Toutes sections CR : exercice complet vs Budget vs N-1' },
  { id: 'ind', name: 'Industrie', cat: 'Sectoriel', desc: 'Production, MP, marge industrielle' },
  { id: 'btp', name: 'BTP', cat: 'Sectoriel', desc: 'Travaux, sous-traitance, chantiers' },
  { id: 'com', name: 'Commerce', cat: 'Sectoriel', desc: 'Marge commerciale, taux de marque' },
  { id: 'mfi', name: 'Microfinance', cat: 'Sectoriel', desc: 'PNB, encours, PAR' },
  { id: 'imco', name: 'Immobilier commercial', cat: 'Sectoriel', desc: 'Loyers, taux occupation, rentabilité m²' },
  { id: 'hot', name: 'Hôtellerie & Restauration', cat: 'Sectoriel', desc: 'RevPAR, ADR, GOP, F&B ratio' },
  { id: 'agri', name: 'Agriculture', cat: 'Sectoriel', desc: 'Production, intrants, rendement' },
  { id: 'sante', name: 'Santé', cat: 'Sectoriel', desc: 'Actes, recettes, personnel soignant' },
  { id: 'transp', name: 'Transport & Logistique', cat: 'Sectoriel', desc: 'CA/km, flotte, carburant' },
  { id: 'serv', name: 'Services & Conseil', cat: 'Sectoriel', desc: 'Honoraires, taux facturable, marge projets' },
  { id: 'ana_centres', name: 'Centres de coûts / profit', cat: 'Analytique', desc: 'Charges & produits par centre' },
  { id: 'ana_projets', name: 'Suivi par projet', cat: 'Analytique', desc: 'Rentabilité, marge, avancement' },
  { id: 'ana_axes', name: 'Axes analytiques', cat: 'Analytique', desc: 'Analyse multi-axes' },
  // ─── États SYSCOHADA + Reporting avancé (Phase 4) ───
  { id: 'tft_monthly', name: 'TFT mensuel ★', cat: 'SYSCOHADA', desc: 'Tableau Flux Trésorerie 12 mois — exploitation/investissement/financement' },
  { id: 'cap_var', name: 'Variation capitaux propres ★', cat: 'SYSCOHADA', desc: 'État obligatoire — apports, distributions, affectation résultat' },
  { id: 'closing_pack', name: 'Closing Pack ★', cat: 'SYSCOHADA', desc: 'Synthèse 1 page A4 — KPIs, charts, alertes' },
  { id: 'tafire', name: 'TAFIRE ★', cat: 'SYSCOHADA', desc: 'Tableau Financier Ressources & Emplois (art. 29-37)' },
  { id: 'bilan_monthly', name: 'Bilan mensuel ★', cat: 'SYSCOHADA', desc: 'Évolution actif/passif sur 12 mois' },
  { id: 'caf', name: 'CAF mensuelle ★', cat: 'SYSCOHADA', desc: 'Capacité d\'autofinancement mensuelle' },
  { id: 'multi_year', name: 'Comparaison N / N-1 / N-2 ★', cat: 'SYSCOHADA', desc: 'Évolution pluriannuelle SIG, ratios et structure' },
  { id: 'bank_recon', name: 'Rapprochement bancaire', cat: 'Audit', desc: 'État de rapprochement GL ↔ relevé' },
  { id: 'closing_just', name: 'Justification de clôture', cat: 'Audit', desc: 'Provisions, CCA/PCA, FAE/FAP' },
  { id: 'audit_visu', name: 'Audit Trail visualizer ★', cat: 'Audit', desc: 'Vérification chaîne de hash SHA-256 du GL' },
  { id: 'anomalies', name: 'Carte des anomalies ★', cat: 'Audit', desc: 'Heatmap mois × catégories d\'anomalies' },
  { id: 'lettrage', name: 'Lettrage tiers', cat: 'Audit', desc: 'Taux de lettrage et vieillissement par tiers' },
  { id: 'zscore', name: 'Score de santé financière ★', cat: 'Premium', desc: 'Z-Score Altman + score Cockpit 0-100' },
  { id: 'forecast', name: 'Rolling Forecast 90j ★', cat: 'Premium', desc: 'Projection trésorerie 30/60/90 jours' },
  { id: 'wcd', name: 'Working Capital Days ★', cat: 'Premium', desc: 'DSO + DIO + DPO + Cash Conversion Cycle' },
  { id: 'seasonality', name: 'Saisonnalité', cat: 'Pilotage', desc: 'Index de saisonnalité du CA — base 100' },
  { id: 'whatif', name: 'What-If / Sensibilité', cat: 'Pilotage', desc: 'Simulation tarifaire — sliders CA/marge/charges' },
  { id: 'provisions', name: 'Provisions tracking', cat: 'Pilotage', desc: 'Suivi dotations / reprises (68x/78x)' },
  { id: 'intercos', name: 'Intercos / CCA', cat: 'Pilotage', desc: 'Comptes courants associés intra-groupe' },
  { id: 'weekly', name: 'Flash hebdo ★', cat: 'Direction', desc: 'Tableau bord hebdomadaire Direction' },
  { id: 'mda', name: 'MD&A auto-généré ★', cat: 'Direction', desc: 'Management Discussion & Analysis — narratif Proph3t' },
  { id: 'board_pack', name: 'Board Pack ★', cat: 'Direction', desc: 'Synthèse 4 slides Conseil d\'Administration' },
  { id: 'sector_bench', name: 'Comparatif sectoriel ★', cat: 'Direction', desc: 'Ratios vs normes UEMOA OHADA par secteur' },
];

// Helper pour KPIs calculés
export const computeKPIs = (data: any) => {
  const sig = data?.sig;
  const bilan = data;
  if (!sig) return {
    ca: '—', rn: '—', ebe: '—', va: '—', mb: '—',
    treso: '—', bfr: '—', actif: '—', capPropres: '—', dso: '—',
  };
  const get = (lines: any[], code: string) => lines?.find((l: any) => l.code === code)?.value ?? 0;
  const treso = get(bilan?.bilanActif, '_BT') - get(bilan?.bilanPassif, 'DV');
  const actifCirc = get(bilan?.bilanActif, '_BK');
  const passifCirc = get(bilan?.bilanPassif, '_DP');
  const bfr = actifCirc - passifCirc;
  return {
    ca: fmtMoney(sig.ca ?? 0),
    rn: fmtMoney(sig.resultat ?? 0),
    ebe: fmtMoney(sig.ebe ?? 0),
    va: fmtMoney(sig.valeurAjoutee ?? 0),
    mb: fmtMoney(sig.margeBrute ?? 0),
    treso: fmtMoney(treso),
    bfr: fmtMoney(bfr),
    actif: fmtMoney(get(bilan?.bilanActif, '_BZ')),
    capPropres: fmtMoney(get(bilan?.bilanPassif, '_CP')),
    dso: data?.ratios?.find((r: any) => r.code === 'DSO')?.value ? `${Math.round(data.ratios.find((r: any) => r.code === 'DSO').value)} j` : '—',
    margePct: sig.ca ? `${((sig.resultat / sig.ca) * 100).toFixed(1)} %` : '—',
    ebePct: sig.ca ? `${((sig.ebe / sig.ca) * 100).toFixed(1)} %` : '—',
  } as Record<string, string>;
};

// Métadonnées par défaut pour chaque modèle rapide
export const TEMPLATE_DEFAULTS: Record<string, { title: string; subtitle?: string }> = {
  weekly:       { title: 'Flash hebdomadaire',         subtitle: 'Indicateurs de la semaine' },
  monthly:      { title: 'Rapport mensuel de gestion', subtitle: 'Analyse de performance financière' },
  quarterly:    { title: 'Comité trimestriel',         subtitle: 'Rapport au comité de direction' },
  annual:       { title: 'Rapport annuel',             subtitle: 'Synthèse de l\'exercice' },
  interim:      { title: 'Rapport intérimaire',        subtitle: 'Synthèse de la période' },
  cfo:          { title: 'Rapport CFO',                subtitle: 'Deep dive Direction Financière' },
  bank:         { title: 'Pack Banque',                subtitle: 'Document à destination de la relation bancaire' },
  audit:        { title: "Rapport au Comité d'Audit",  subtitle: "Contrôles, anomalies et plan de remédiation" },
  shareholders: { title: 'Reporting Actionnaires',     subtitle: 'Synthèse pour les actionnaires' },
  board:        { title: "Conseil d'Administration",   subtitle: 'Synthèse compacte 4 slides' },
  fiscal:       { title: 'Pack Fiscal',                subtitle: 'TVA, IS, charges fiscales et risques' },
  closing:      { title: 'Closing Mensuel',            subtitle: 'Pack de clôture et justifications' },
  cash:         { title: 'Cash Management',            subtitle: 'Trésorerie, prévisions et optimisation' },
  ifrs:         { title: 'États financiers IFRS',      subtitle: 'Converted from revised SYSCOHADA — IAS/IFRS presentation' },
};

export function uid() { return Math.random().toString(36).substring(2, 11); }

export function filterConditionalBlocks(blocks: Block[], data: any): Block[] {
  const noStocks = !data?.hasStocks;
  const noAnalytical = !data?.hasAnalytical;
  if (!noStocks && !noAnalytical) return blocks;

  const sectionsToRemove: { keyword: RegExp; condition: boolean }[] = [];
  if (noStocks) sectionsToRemove.push({ keyword: /\bstocks?\b/i, condition: true });
  if (noAnalytical) sectionsToRemove.push({ keyword: /analytiq/i, condition: true });

  const result: Block[] = [];
  let skipUntilNextPageBreak = false;
  for (let i = 0; i < blocks.length; i++) {
    const b = blocks[i];
    if (skipUntilNextPageBreak) {
      if (b.type === 'pageBreak') skipUntilNextPageBreak = false;
      continue;
    }
    if (b.type === 'h1') {
      const text = ((b as any).text || '') as string;
      const matchSection = sectionsToRemove.find((s) => s.keyword.test(text));
      if (matchSection) {
        if (result.length > 0 && result[result.length - 1].type === 'pageBreak') {
          result.pop();
        }
        skipUntilNextPageBreak = true;
        continue;
      }
    }
    result.push(b);
  }
  return result;
}

// ─── QUICK TEMPLATES ─────────────────────────────────────────────
export const QUICK_TEMPLATES: Record<string, (data?: any) => Block[]> = {
  weekly: (data) => {
    const k = computeKPIs(data);
    return [
      { id: uid(), type: 'h1', text: '1. Synthèse hebdomadaire', inToc: true },
      { id: uid(), type: 'paragraph', text: "Flash de la semaine : indicateurs clés, position de trésorerie, alertes et suivi des créances." },
      { id: uid(), type: 'kpi', items: [
        { label: "Chiffre d'affaires", value: k.ca, subValue: 'Cumul YTD' },
        { label: 'Résultat net', value: k.rn, subValue: `Marge ${k.margePct}` },
        { label: 'Trésorerie nette', value: k.treso },
        { label: 'BFR', value: k.bfr },
      ]},
      { id: uid(), type: 'kpi', items: [
        { label: 'EBE', value: k.ebe, subValue: `Taux ${k.ebePct}` },
        { label: 'DSO', value: k.dso, subValue: 'Délai clients' },
        { label: 'Total Actif', value: k.actif },
        { label: 'Capitaux propres', value: k.capPropres },
      ]},
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '2. Ratios et alertes', inToc: true },
      { id: uid(), type: 'table', source: 'ratios', title: 'Ratios financiers' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '3. Position de trésorerie', inToc: true },
      { id: uid(), type: 'dashboard', dashboardId: 'cashflow', title: 'Cashflow Statement' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '4. Suivi des créances et dettes', inToc: true },
      { id: uid(), type: 'dashboard', dashboardId: 'receivables', title: 'Receivables & Payables' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '5. Stocks', inToc: true },
      { id: uid(), type: 'dashboard', dashboardId: 'stk', title: 'Stocks — valorisation et rotation' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '6. Points d\'attention', inToc: true },
      { id: uid(), type: 'paragraph', text: "Synthèse des alertes et actions de la semaine. À compléter par le contrôle de gestion." },
    ];
  },

  monthly: (data) => {
    const k = computeKPIs(data);
    return [
      { id: uid(), type: 'h1', text: '1. Synthèse exécutive', inToc: true },
      { id: uid(), type: 'paragraph', text: "Le présent rapport présente la performance financière de la société sur la période. Il analyse les principaux indicateurs de gestion, l'évolution de la trésorerie et les écarts par rapport au budget." },
      { id: uid(), type: 'kpi', items: [
        { label: "Chiffre d'affaires", value: k.ca, subValue: 'Cumul de la période' },
        { label: 'Résultat net', value: k.rn, subValue: `Marge ${k.margePct}` },
        { label: 'EBE', value: k.ebe, subValue: `Taux ${k.ebePct}` },
        { label: 'Trésorerie nette', value: k.treso },
      ]},
      { id: uid(), type: 'dashboard', dashboardId: 'exec', title: 'Vue exécutive — KPIs, radar, alertes' },
      { id: uid(), type: 'h2', text: '1.1 Faits marquants', inToc: true },
      { id: uid(), type: 'paragraph', text: "Éléments significatifs de la période : variations notables, événements exceptionnels, décisions structurantes. À compléter." },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '2. Compte de résultat', inToc: true },
      { id: uid(), type: 'paragraph', text: "Présentation du compte de résultat SYSCOHADA et des soldes intermédiaires de gestion." },
      { id: uid(), type: 'table', source: 'cr', title: 'Compte de résultat — par nature' },
      { id: uid(), type: 'table', source: 'sig', title: 'SIG — formation du résultat' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '3. Waterfall — Cascade SIG', inToc: true },
      { id: uid(), type: 'paragraph', text: "Cascade visuelle du chiffre d'affaires au résultat net via les soldes intermédiaires." },
      { id: uid(), type: 'dashboard', dashboardId: 'waterfall', title: 'Waterfall — du CA au RN' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '4. Analyse du CR par bloc', inToc: true },
      { id: uid(), type: 'paragraph', text: "Décomposition du compte de résultat par section. Format : Actual / Budget / N-1 (mois + YTD)." },
      { id: uid(), type: 'dashboard', dashboardId: 'crblock', title: 'CR — Analyse par bloc' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h2', text: "4.1 Produits d'exploitation — Mensuel", inToc: true },
      { id: uid(), type: 'table', source: 'crtab_produits_expl_m', title: "Produits d'exploitation (70-75) — Month + YTD" },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h2', text: "4.2 Charges d'exploitation — Mensuel", inToc: true },
      { id: uid(), type: 'table', source: 'crtab_charges_expl_m', title: "Charges d'exploitation (60-66) — Month + YTD" },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h2', text: '4.3 Produits financiers — Mensuel', inToc: true },
      { id: uid(), type: 'table', source: 'crtab_produits_fin_m', title: 'Produits financiers (77) — Month + YTD' },
      { id: uid(), type: 'h2', text: '4.4 Charges financières — Mensuel', inToc: true },
      { id: uid(), type: 'table', source: 'crtab_charges_fin_m', title: 'Charges financières (67) — Month + YTD' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '5. Seuil de rentabilité', inToc: true },
      { id: uid(), type: 'paragraph', text: "Point mort, marge de sécurité et structure des coûts fixes/variables." },
      { id: uid(), type: 'dashboard', dashboardId: 'breakeven', title: 'Seuil de rentabilité' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '6. Pareto des comptes (ABC)', inToc: true },
      { id: uid(), type: 'paragraph', text: "Top 20 % des comptes qui pèsent 80 % du CA et des charges (loi de Pareto)." },
      { id: uid(), type: 'dashboard', dashboardId: 'pareto', title: 'Analyse ABC — Pareto' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '7. Position financière — Bilan', inToc: true },
      { id: uid(), type: 'paragraph', text: "Bilan SYSCOHADA — Actif et Passif aux normes OHADA révisé 2017. Tous les montants sont exprimés en franc CFA (XOF)." },
      { id: uid(), type: 'table', source: 'bilan_actif', title: 'Bilan — Actif' },
      { id: uid(), type: 'table', source: 'bilan_passif', title: 'Bilan — Passif' },
      { id: uid(), type: 'kpi', items: [
        { label: 'Total Actif', value: k.actif }, { label: 'Capitaux propres', value: k.capPropres },
        { label: 'BFR', value: k.bfr, subValue: "d'exploitation" }, { label: 'Trésorerie nette', value: k.treso },
      ]},
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: "7.1 Structure de l'Actif", inToc: true },
      { id: uid(), type: 'dashboard', dashboardId: 'struct_actif', title: "Structure de l'Actif" },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '7.2 Structure du Passif', inToc: true },
      { id: uid(), type: 'dashboard', dashboardId: 'struct_passif', title: 'Structure du Passif' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '8. Trésorerie & BFR', inToc: true },
      { id: uid(), type: 'dashboard', dashboardId: 'cashflow', title: 'Cashflow Statement' },
      { id: uid(), type: 'dashboard', dashboardId: 'bfr', title: 'FR, BFR, TN' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '9. Cycle clients', inToc: true },
      { id: uid(), type: 'dashboard', dashboardId: 'client', title: 'Créances, DSO, balance âgée' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '10. Pyramide des performances', inToc: true },
      { id: uid(), type: 'dashboard', dashboardId: 'pyramide_perf', title: 'ROE = Marge × Rotation × Levier' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '11. Budget vs Réalisé', inToc: true },
      { id: uid(), type: 'dashboard', dashboardId: 'is_bvsa', title: 'Budget vs Actual (annuel)' },
      { id: uid(), type: 'dashboard', dashboardId: 'is_bvsa_monthly', title: 'Budget vs Réalisé mensuel + N-1' },
      { id: uid(), type: 'table', source: 'budget_actual', title: 'Détail écarts par compte' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '12. Cycle fournisseurs', inToc: true },
      { id: uid(), type: 'dashboard', dashboardId: 'fr', title: 'Dettes fournisseurs, échéances' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '13. Masse salariale et charges sociales', inToc: true },
      { id: uid(), type: 'dashboard', dashboardId: 'sal', title: 'Charges de personnel' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '14. Comptabilité analytique', inToc: true },
      { id: uid(), type: 'paragraph', text: "Ventilation des charges et produits par centre de coût, projet ou département." },
      { id: uid(), type: 'dashboard', dashboardId: 'analytical', title: 'P&L par section analytique' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '15. Immobilisations', inToc: true },
      { id: uid(), type: 'dashboard', dashboardId: 'immo', title: 'VNC, amortissements, taux de vétusté' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '15. Fiscalité', inToc: true },
      { id: uid(), type: 'dashboard', dashboardId: 'fis', title: 'TVA, IS, pression fiscale' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '16. Stocks', inToc: true },
      { id: uid(), type: 'dashboard', dashboardId: 'stk', title: 'Valorisation, dépréciations, rotation' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '17. Ratios financiers', inToc: true },
      { id: uid(), type: 'table', source: 'ratios', title: 'Ratios financiers' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '18. Balance générale', inToc: true },
      { id: uid(), type: 'table', source: 'balance', title: 'Balance générale' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '19. Conclusions et recommandations', inToc: true },
      { id: uid(), type: 'paragraph', text: "Synthèse de l'exercice, points d'attention, risques identifiés et plan d'action pour le prochain exercice." },
      { id: uid(), type: 'h2', text: "Principaux risques", inToc: true },
      { id: uid(), type: 'paragraph', text: "À compléter : risques identifiés (liquidité, concentration tiers, fiscalité, opérationnel)." },
      { id: uid(), type: 'h2', text: "Plan d'action", inToc: true },
      { id: uid(), type: 'paragraph', text: "À compléter : actions correctives, responsables, échéances, indicateurs de suivi." },
      { id: uid(), type: 'h2', text: "Perspectives", inToc: true },
      { id: uid(), type: 'paragraph', text: "À compléter : objectifs du prochain exercice, investissements prévus, évolution du CA et de la rentabilité." },
    ];
  },

  quarterly: (data) => {
    const k = computeKPIs(data);
    return [
      { id: uid(), type: 'h1', text: '1. Synthèse du trimestre', inToc: true },
      { id: uid(), type: 'paragraph', text: "Rapport trimestriel de performance financière. Analyse de la performance, de la structure financière et des indicateurs clés pour le comité de direction." },
      { id: uid(), type: 'kpi', items: [
        { label: "CA trimestre", value: k.ca, subValue: 'Cumul YTD' },
        { label: 'Résultat net', value: k.rn, subValue: `Marge ${k.margePct}` },
        { label: 'EBE', value: k.ebe, subValue: `Taux ${k.ebePct}` },
        { label: 'Trésorerie nette', value: k.treso },
      ]},
      { id: uid(), type: 'dashboard', dashboardId: 'exec', title: 'Vue exécutive' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '2. Performance — CR trimestriel', inToc: true },
      { id: uid(), type: 'dashboard', dashboardId: 'crblock_quarterly', title: 'CR Bloc — Quarterly' },
      { id: uid(), type: 'table', source: 'crtab_produits_expl_q', title: "Produits d'exploitation — Quarterly" },
      { id: uid(), type: 'table', source: 'crtab_charges_expl_q', title: "Charges d'exploitation — Quarterly" },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '3. Position financière', inToc: true },
      { id: uid(), type: 'table', source: 'bilan_actif', title: 'Bilan — Actif' },
      { id: uid(), type: 'table', source: 'bilan_passif', title: 'Bilan — Passif' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '4. Budget vs Réalisé', inToc: true },
      { id: uid(), type: 'dashboard', dashboardId: 'is_bvsa', title: 'Budget vs Actual — annuel' },
      { id: uid(), type: 'dashboard', dashboardId: 'is_bvsa_monthly', title: 'Budget vs Réalisé mensuel + N-1' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '5. Trésorerie', inToc: true },
      { id: uid(), type: 'dashboard', dashboardId: 'cashflow', title: 'Cashflow Statement' },
      { id: uid(), type: 'dashboard', dashboardId: 'bfr', title: 'FR, BFR, TN' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '6. Cycle client & fournisseur', inToc: true },
      { id: uid(), type: 'dashboard', dashboardId: 'client', title: 'Cycle Client — DSO' },
      { id: uid(), type: 'dashboard', dashboardId: 'fr', title: 'Cycle Fournisseur — DPO' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '7. Ratios et score', inToc: true },
      { id: uid(), type: 'table', source: 'ratios', title: 'Ratios financiers' },
      { id: uid(), type: 'dashboard', dashboardId: 'zscore', title: 'Score de santé financière' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '8. Perspectives et plan d\'action', inToc: true },
      { id: uid(), type: 'paragraph', text: "À compléter : revue des objectifs annuels, réajustements éventuels, actions prioritaires pour le prochain trimestre." },
    ];
  },

  annual: (data) => {
    const k = computeKPIs(data);
    return [
      { id: uid(), type: 'h1', text: '1. Synthèse de l\'exercice', inToc: true },
      { id: uid(), type: 'paragraph', text: "Rapport annuel de la société. Synthèse de l'exercice écoulé : performance financière, position financière, création de valeur et perspectives." },
      { id: uid(), type: 'kpi', items: [
        { label: "Chiffre d'affaires", value: k.ca, subValue: 'Exercice complet' },
        { label: 'Résultat net', value: k.rn, subValue: `Marge ${k.margePct}` },
        { label: 'EBE', value: k.ebe, subValue: `Taux ${k.ebePct}` },
        { label: 'Trésorerie nette', value: k.treso },
      ]},
      { id: uid(), type: 'kpi', items: [
        { label: 'Total Actif', value: k.actif }, { label: 'Capitaux propres', value: k.capPropres },
        { label: 'BFR', value: k.bfr }, { label: 'DSO', value: k.dso },
      ]},
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '2. Compte de résultat annuel', inToc: true },
      { id: uid(), type: 'table', source: 'cr', title: 'Compte de résultat — exercice complet' },
      { id: uid(), type: 'table', source: 'sig', title: 'SIG — formation du résultat' },
      { id: uid(), type: 'dashboard', dashboardId: 'waterfall', title: 'Cascade SIG — du CA au RN' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '3. CR Annuel par section', inToc: true },
      { id: uid(), type: 'dashboard', dashboardId: 'crblock_annual', title: 'CR Bloc — Annual' },
      { id: uid(), type: 'table', source: 'crtab_produits_expl_a', title: "Produits d'exploitation — Annual" },
      { id: uid(), type: 'table', source: 'crtab_charges_expl_a', title: "Charges d'exploitation — Annual" },
      { id: uid(), type: 'table', source: 'crtab_produits_fin_a', title: 'Produits financiers — Annual' },
      { id: uid(), type: 'table', source: 'crtab_charges_fin_a', title: 'Charges financières — Annual' },
      { id: uid(), type: 'table', source: 'crtab_impots_a', title: 'Impôts — Annual' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '4. Bilan SYSCOHADA', inToc: true },
      { id: uid(), type: 'table', source: 'bilan_actif', title: 'Bilan — Actif' },
      { id: uid(), type: 'table', source: 'bilan_passif', title: 'Bilan — Passif' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '5. Structure financière', inToc: true },
      { id: uid(), type: 'dashboard', dashboardId: 'struct_actif', title: "Structure de l'Actif" },
      { id: uid(), type: 'dashboard', dashboardId: 'struct_passif', title: 'Structure du Passif' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '6. Tableau des flux de trésorerie', inToc: true },
      { id: uid(), type: 'table', source: 'tft', title: 'TFT — méthode indirecte' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '7. Variation des capitaux propres', inToc: true },
      { id: uid(), type: 'table', source: 'capital', title: 'Variation des capitaux propres' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '8. Comparaison pluriannuelle', inToc: true },
      { id: uid(), type: 'dashboard', dashboardId: 'multi_year', title: 'N / N-1 / N-2' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '9. Pyramide des performances', inToc: true },
      { id: uid(), type: 'dashboard', dashboardId: 'pyramide_perf', title: 'ROE = Marge × Rotation × Levier' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '10. Ratios et score de santé', inToc: true },
      { id: uid(), type: 'table', source: 'ratios', title: 'Ratios financiers' },
      { id: uid(), type: 'dashboard', dashboardId: 'zscore', title: 'Score de santé financière' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '11. Trésorerie', inToc: true },
      { id: uid(), type: 'dashboard', dashboardId: 'cashflow', title: 'Cashflow Statement' },
      { id: uid(), type: 'dashboard', dashboardId: 'bfr', title: 'FR, BFR, TN' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '12. Cycle clients', inToc: true },
      { id: uid(), type: 'dashboard', dashboardId: 'client', title: 'DSO + balance âgée' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '13. Budget vs Réalisé', inToc: true },
      { id: uid(), type: 'dashboard', dashboardId: 'is_bvsa', title: 'Budget vs Actual (annuel)' },
      { id: uid(), type: 'table', source: 'budget_actual', title: 'Détail des écarts' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '14. Conformité SYSCOHADA', inToc: true },
      { id: uid(), type: 'dashboard', dashboardId: 'compliance', title: 'Compliance — 10 contrôles' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '15. Balance générale', inToc: true },
      { id: uid(), type: 'table', source: 'balance', title: 'Balance générale' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '16. Conclusions et perspectives', inToc: true },
      { id: uid(), type: 'paragraph', text: "Synthèse de l'exercice. À compléter : faits marquants, décisions de l'Assemblée Générale, objectifs du prochain exercice." },
    ];
  },

  interim: (data) => {
    const k = computeKPIs(data);
    return [
      { id: uid(), type: 'h1', text: '1. Synthèse de la période', inToc: true },
      { id: uid(), type: 'paragraph', text: "Rapport intérimaire de la société sur la période de reporting sélectionnée. Analyse de la performance, de la position financière et des perspectives." },
      { id: uid(), type: 'kpi', items: [
        { label: 'CA période', value: k.ca, subValue: 'Cumul période' }, { label: 'RN', value: k.rn, subValue: `Marge ${k.margePct}` },
        { label: 'EBE', value: k.ebe, subValue: `Taux ${k.ebePct}` }, { label: 'Trésorerie', value: k.treso },
      ]},
      { id: uid(), type: 'kpi', items: [
        { label: 'Total Actif', value: k.actif }, { label: 'Capitaux propres', value: k.capPropres },
        { label: 'BFR', value: k.bfr }, { label: 'DSO', value: k.dso },
      ]},
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '2. Bilan intérimaire', inToc: true },
      { id: uid(), type: 'table', source: 'bilan_actif', title: 'Bilan — Actif (arrêté de période)' },
      { id: uid(), type: 'table', source: 'bilan_passif', title: 'Bilan — Passif (arrêté de période)' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '3. Compte de résultat de la période', inToc: true },
      { id: uid(), type: 'table', source: 'cr', title: 'Compte de résultat — par nature' },
      { id: uid(), type: 'table', source: 'sig', title: 'Soldes intermédiaires de gestion' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '4. Analyse du CR par section — Interim', inToc: true },
      { id: uid(), type: 'dashboard', dashboardId: 'crblock_interim', title: 'CR Bloc — Interim' },
      { id: uid(), type: 'table', source: 'crtab_produits_expl_s', title: "Produits d'exploitation — Interim" },
      { id: uid(), type: 'table', source: 'crtab_charges_expl_s', title: "Charges d'exploitation — Interim" },
      { id: uid(), type: 'table', source: 'crtab_produits_fin_s', title: 'Produits financiers — Interim' },
      { id: uid(), type: 'table', source: 'crtab_charges_fin_s', title: 'Charges financières — Interim' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '5. Tableau des flux de trésorerie', inToc: true },
      { id: uid(), type: 'table', source: 'tft', title: 'TFT — période' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '6. Budget vs Réalisé', inToc: true },
      { id: uid(), type: 'dashboard', dashboardId: 'is_bvsa', title: 'Budget vs Actual' },
      { id: uid(), type: 'dashboard', dashboardId: 'is_bvsa_monthly', title: 'Budget vs Réalisé — Mensuel + N-1' },
      { id: uid(), type: 'table', source: 'budget_actual', title: 'Détail par compte' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '7. Trésorerie et flux', inToc: true },
      { id: uid(), type: 'dashboard', dashboardId: 'cashflow', title: 'Cashflow' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '8. Cycle clients', inToc: true },
      { id: uid(), type: 'dashboard', dashboardId: 'client', title: 'Créances et recouvrement' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '9. Cycle fournisseurs', inToc: true },
      { id: uid(), type: 'dashboard', dashboardId: 'fr', title: 'Dettes fournisseurs' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '10. BFR et fonds de roulement', inToc: true },
      { id: uid(), type: 'dashboard', dashboardId: 'bfr', title: 'FR, BFR, TN' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '11. Stocks', inToc: true },
      { id: uid(), type: 'dashboard', dashboardId: 'stk', title: 'Stocks — valorisation et rotation' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '12. Ratios financiers', inToc: true },
      { id: uid(), type: 'table', source: 'ratios', title: 'Ratios financiers — période' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '13. Prévisions et perspectives', inToc: true },
      { id: uid(), type: 'paragraph', text: "Projections basées sur les tendances observées sur la période. À compléter avec les hypothèses de la Direction." },
      { id: uid(), type: 'h2', text: 'Objectifs période suivante', inToc: true },
      { id: uid(), type: 'paragraph', text: "À compléter : CA prévisionnel, charges cibles, investissements planifiés, recrutements." },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '14. Recommandations', inToc: true },
      { id: uid(), type: 'paragraph', text: "Points d'attention et actions correctives pour la période suivante." },
    ];
  },

  cfo: (data) => {
    const k = computeKPIs(data);
    return [
      { id: uid(), type: 'h1', text: '1. Synthèse CFO', inToc: true },
      { id: uid(), type: 'paragraph', text: "Tableau de bord du Directeur Financier. Vision opérationnelle profonde sur la performance, la liquidité, la rentabilité et la création de valeur." },
      { id: uid(), type: 'kpi', items: [
        { label: 'CA YTD', value: k.ca, subValue: 'Cumul' }, { label: 'EBE', value: k.ebe, subValue: `Taux ${k.ebePct}` },
        { label: 'RN', value: k.rn, subValue: `Marge ${k.margePct}` }, { label: 'Trésorerie', value: k.treso },
      ]},
      { id: uid(), type: 'kpi', items: [
        { label: 'BFR', value: k.bfr }, { label: 'DSO', value: k.dso, subValue: 'Délai clients' },
        { label: 'Total Actif', value: k.actif }, { label: 'Capitaux propres', value: k.capPropres },
      ]},
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '2. Score de santé financière', inToc: true },
      { id: uid(), type: 'dashboard', dashboardId: 'zscore', title: 'Score financier global' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '3. Cascade SIG — Du CA au Résultat Net', inToc: true },
      { id: uid(), type: 'dashboard', dashboardId: 'waterfall', title: 'Waterfall SIG' },
      { id: uid(), type: 'table', source: 'sig', title: 'Soldes intermédiaires de gestion' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '4. Working Capital Days', inToc: true },
      { id: uid(), type: 'dashboard', dashboardId: 'wcd', title: 'DSO / DIO / DPO / CCC' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '5. Rolling Forecast 90 jours', inToc: true },
      { id: uid(), type: 'dashboard', dashboardId: 'forecast', title: 'Forecast trésorerie 90j' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '6. Pareto des comptes (ABC)', inToc: true },
      { id: uid(), type: 'dashboard', dashboardId: 'pareto', title: 'Top 20% des comptes = 80% du CA/charges' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '7. Seuil de rentabilité', inToc: true },
      { id: uid(), type: 'dashboard', dashboardId: 'breakeven', title: 'Point mort + marge de sécurité' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '8. Performance vs Budget', inToc: true },
      { id: uid(), type: 'dashboard', dashboardId: 'is_bvsa', title: 'Budget vs Actual (annuel)' },
      { id: uid(), type: 'dashboard', dashboardId: 'is_bvsa_monthly', title: 'Budget vs Réalisé mensuel + N-1' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '9. Ratios financiers', inToc: true },
      { id: uid(), type: 'table', source: 'ratios', title: 'Tableau des ratios' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '10. Décisions et arbitrages CFO', inToc: true },
      { id: uid(), type: 'paragraph', text: "À compléter." },
    ];
  },

  bank: (data) => {
    const k = computeKPIs(data);
    return [
      { id: uid(), type: 'h1', text: '1. Synthèse à l\'attention de la banque', inToc: true },
      { id: uid(), type: 'paragraph', text: "Document destiné à la relation bancaire : structure financière, liquidité, capacité de remboursement, respect des covenants." },
      { id: uid(), type: 'kpi', items: [
        { label: "Chiffre d'affaires", value: k.ca, subValue: 'Cumul YTD' },
        { label: 'EBE', value: k.ebe, subValue: `Taux ${k.ebePct}` },
        { label: 'Capitaux propres', value: k.capPropres },
        { label: 'Total bilan', value: k.actif },
      ]},
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '2. Position de trésorerie', inToc: true },
      { id: uid(), type: 'dashboard', dashboardId: 'tre', title: 'Trésorerie — position et flux' },
      { id: uid(), type: 'dashboard', dashboardId: 'cashflow', title: 'Cashflow Statement' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '3. Plan de trésorerie 13 semaines', inToc: true },
      { id: uid(), type: 'dashboard', dashboardId: 'cashforecast', title: 'Cashflow prévisionnel 13 semaines' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '4. Rolling Forecast 90 jours', inToc: true },
      { id: uid(), type: 'dashboard', dashboardId: 'forecast', title: 'Forecast 30/60/90 jours' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '5. Capacité de remboursement', inToc: true },
      { id: uid(), type: 'dashboard', dashboardId: 'zscore', title: 'Score financier global (Z-Score)' },
      { id: uid(), type: 'table', source: 'ratios', title: 'Ratios de solvabilité' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '6. Structure financière', inToc: true },
      { id: uid(), type: 'dashboard', dashboardId: 'struct_passif', title: 'Structure du Passif (CP / Dettes)' },
      { id: uid(), type: 'dashboard', dashboardId: 'bfr', title: 'FR / BFR / TN' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '7. Bilan synthétique', inToc: true },
      { id: uid(), type: 'table', source: 'bilan_actif', title: 'Bilan — Actif' },
      { id: uid(), type: 'table', source: 'bilan_passif', title: 'Bilan — Passif' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '8. Compte de résultat synthétique', inToc: true },
      { id: uid(), type: 'table', source: 'cr', title: 'CR par nature' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '9. Cycle clients (recouvrement)', inToc: true },
      { id: uid(), type: 'dashboard', dashboardId: 'client', title: 'DSO + balance âgée' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '10. Bank Reconciliation', inToc: true },
      { id: uid(), type: 'dashboard', dashboardId: 'bank_recon', title: 'Rapprochement bancaire — vérification soldes' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '11. Engagements et garanties', inToc: true },
      { id: uid(), type: 'paragraph', text: "À compléter : encours emprunts par établissement, échéancier, garanties consenties, covenants." },
    ];
  },

  audit: (data) => {
    const k = computeKPIs(data);
    return [
      { id: uid(), type: 'h1', text: '1. Synthèse Comité d\'Audit', inToc: true },
      { id: uid(), type: 'paragraph', text: "Rapport au Comité d'Audit : intégrité des données, conformité SYSCOHADA, anomalies détectées, plan de remédiation." },
      { id: uid(), type: 'kpi', items: [
        { label: "Total Actif", value: k.actif }, { label: 'Total CR', value: k.ca },
        { label: 'Trésorerie', value: k.treso }, { label: 'Capitaux propres', value: k.capPropres },
      ]},
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '2. Conformité SYSCOHADA', inToc: true },
      { id: uid(), type: 'dashboard', dashboardId: 'compliance', title: 'Compliance SYSCOHADA — 10 contrôles' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '3. Audit Trail — chaîne de hash SHA-256', inToc: true },
      { id: uid(), type: 'dashboard', dashboardId: 'audit_visu', title: 'Vérification chaîne de hash GL' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '4. Carte des anomalies', inToc: true },
      { id: uid(), type: 'dashboard', dashboardId: 'anomalies', title: 'Anomalies détectées' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '5. Lettrage tiers', inToc: true },
      { id: uid(), type: 'dashboard', dashboardId: 'lettrage', title: 'Taux de lettrage et vieillissement' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '6. Intercos / Comptes courants associés', inToc: true },
      { id: uid(), type: 'dashboard', dashboardId: 'intercos', title: 'Comptes intra-groupe' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '7. Justifications de clôture', inToc: true },
      { id: uid(), type: 'dashboard', dashboardId: 'closing_just', title: 'Provisions et régularisations' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '8. Pareto des comptes', inToc: true },
      { id: uid(), type: 'dashboard', dashboardId: 'pareto', title: 'Top 20% des comptes (priorité audit)' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '9. Bilan détaillé', inToc: true },
      { id: uid(), type: 'table', source: 'bilan_actif', title: 'Bilan — Actif' },
      { id: uid(), type: 'table', source: 'bilan_passif', title: 'Bilan — Passif' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '10. Balance générale', inToc: true },
      { id: uid(), type: 'table', source: 'balance', title: 'Balance générale' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '11. Plan de remédiation', inToc: true },
      { id: uid(), type: 'paragraph', text: "À compléter : actions correctives sur les anomalies critiques, responsables, échéances." },
    ];
  },

  shareholders: (data) => {
    const k = computeKPIs(data);
    return [
      { id: uid(), type: 'h1', text: '1. Message aux actionnaires', inToc: true },
      { id: uid(), type: 'paragraph', text: "Synthèse de la performance à destination des actionnaires. À compléter par la Direction Générale." },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '2. Indicateurs clés', inToc: true },
      { id: uid(), type: 'kpi', items: [
        { label: "Chiffre d'affaires", value: k.ca }, { label: 'Résultat net', value: k.rn, subValue: `Marge ${k.margePct}` },
        { label: 'EBE', value: k.ebe, subValue: `Taux ${k.ebePct}` }, { label: 'Capitaux propres', value: k.capPropres },
      ]},
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '3. Performance financière', inToc: true },
      { id: uid(), type: 'dashboard', dashboardId: 'exec', title: 'Vue exécutive' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '4. Cascade SIG', inToc: true },
      { id: uid(), type: 'dashboard', dashboardId: 'waterfall', title: 'Waterfall SIG' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '5. Structure financière', inToc: true },
      { id: uid(), type: 'dashboard', dashboardId: 'struct_actif', title: "Structure de l'Actif" },
      { id: uid(), type: 'dashboard', dashboardId: 'struct_passif', title: 'Structure du Passif' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '6. Variation des capitaux propres', inToc: true },
      { id: uid(), type: 'table', source: 'capital', title: 'Variation des capitaux propres' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '7. Performance vs Budget', inToc: true },
      { id: uid(), type: 'dashboard', dashboardId: 'is_bvsa', title: 'Budget vs Réalisé' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '8. Comparatif sectoriel', inToc: true },
      { id: uid(), type: 'dashboard', dashboardId: 'sector_bench', title: 'Comparatif sectoriel UEMOA' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '9. Score de santé financière', inToc: true },
      { id: uid(), type: 'dashboard', dashboardId: 'zscore', title: 'Score Cockpit + Z-Score' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '10. Perspectives', inToc: true },
      { id: uid(), type: 'paragraph', text: "À compléter : objectifs stratégiques, plan d'investissement, politique de distribution." },
    ];
  },

  board: (data) => {
    const k = computeKPIs(data);
    return [
      { id: uid(), type: 'h1', text: '1. Ordre du jour', inToc: true },
      { id: uid(), type: 'paragraph', text: "Synthèse pour le Conseil d'Administration. Format compact (4 slides clés)." },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '2. Slide 1 — Synthèse exécutive', inToc: true },
      { id: uid(), type: 'kpi', items: [
        { label: "Chiffre d'affaires", value: k.ca, subValue: 'YTD' }, { label: 'Résultat net', value: k.rn, subValue: `Marge ${k.margePct}` },
        { label: 'Trésorerie', value: k.treso }, { label: 'EBE', value: k.ebe, subValue: `Taux ${k.ebePct}` },
      ]},
      { id: uid(), type: 'dashboard', dashboardId: 'board_pack', title: "Board Pack" },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '3. Slide 2 — Performance financière', inToc: true },
      { id: uid(), type: 'dashboard', dashboardId: 'is_bvsa', title: 'Budget vs Réalisé' },
      { id: uid(), type: 'dashboard', dashboardId: 'multi_year', title: 'Évolution N / N-1 / N-2' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '4. Slide 3 — Structure financière', inToc: true },
      { id: uid(), type: 'dashboard', dashboardId: 'struct_actif', title: "Structure Actif" },
      { id: uid(), type: 'dashboard', dashboardId: 'struct_passif', title: 'Structure Passif' },
      { id: uid(), type: 'dashboard', dashboardId: 'bfr', title: 'FR / BFR / TN' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '5. Slide 4 — Risques & Score', inToc: true },
      { id: uid(), type: 'dashboard', dashboardId: 'zscore', title: 'Score de santé financière' },
      { id: uid(), type: 'dashboard', dashboardId: 'sector_bench', title: 'Comparatif sectoriel' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '6. Décisions soumises au Conseil', inToc: true },
      { id: uid(), type: 'paragraph', text: "À compléter : décisions à prendre par le Conseil d'Administration." },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '7. Plan d\'action et suivi', inToc: true },
      { id: uid(), type: 'paragraph', text: "À compléter : actions du précédent Conseil + statut, nouvelles actions, échéances." },
    ];
  },

  fiscal: (data) => {
    const k = computeKPIs(data);
    return [
      { id: uid(), type: 'h1', text: '1. Synthèse fiscale', inToc: true },
      { id: uid(), type: 'paragraph', text: "Pack fiscal de la société : TVA, IS, charges fiscales, situation des déclarations et risques fiscaux identifiés." },
      { id: uid(), type: 'kpi', items: [
        { label: 'CA HT', value: k.ca }, { label: 'Résultat fiscal', value: k.rn },
        { label: 'EBE', value: k.ebe }, { label: 'Capitaux propres', value: k.capPropres },
      ]},
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '2. Position TVA', inToc: true },
      { id: uid(), type: 'dashboard', dashboardId: 'fis', title: 'TVA collectée / déductible / nette' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '3. Impôts sur les bénéfices (IS)', inToc: true },
      { id: uid(), type: 'table', source: 'crtab_impots_a', title: 'Impôts (87, 89) — Annual' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '4. Compte de résultat fiscal', inToc: true },
      { id: uid(), type: 'table', source: 'cr', title: 'CR par nature' },
      { id: uid(), type: 'table', source: 'sig', title: 'Soldes intermédiaires' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '5. Pression fiscale', inToc: true },
      { id: uid(), type: 'table', source: 'ratios', title: 'Ratios fiscaux' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '6. Charges sociales', inToc: true },
      { id: uid(), type: 'dashboard', dashboardId: 'sal', title: 'Masse salariale et charges sociales (66)' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '7. Calendrier des déclarations', inToc: true },
      { id: uid(), type: 'paragraph', text: "À compléter : calendrier TVA mensuelle, IS (acomptes + solde), CFE, taxes diverses." },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '8. Risques fiscaux identifiés', inToc: true },
      { id: uid(), type: 'paragraph', text: "À compléter : risques de redressement, contentieux en cours, provisions fiscales." },
    ];
  },

  closing: (data) => {
    const k = computeKPIs(data);
    return [
      { id: uid(), type: 'h1', text: '1. Closing Pack — Synthèse 1 page', inToc: true },
      { id: uid(), type: 'dashboard', dashboardId: 'closing_pack', title: 'Closing Pack synthétique' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '2. KPI de clôture', inToc: true },
      { id: uid(), type: 'kpi', items: [
        { label: "CA YTD", value: k.ca }, { label: 'EBE', value: k.ebe, subValue: `Taux ${k.ebePct}` },
        { label: 'Résultat net', value: k.rn, subValue: `Marge ${k.margePct}` }, { label: 'Trésorerie', value: k.treso },
      ]},
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '3. Conformité SYSCOHADA', inToc: true },
      { id: uid(), type: 'dashboard', dashboardId: 'compliance', title: 'Compliance SYSCOHADA — 10 contrôles' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '4. Justifications de clôture', inToc: true },
      { id: uid(), type: 'dashboard', dashboardId: 'closing_just', title: 'Provisions et régularisations' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '5. Provisions tracking', inToc: true },
      { id: uid(), type: 'dashboard', dashboardId: 'provisions', title: 'Dotations / Reprises (68x / 78x)' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '6. Rapprochement bancaire', inToc: true },
      { id: uid(), type: 'dashboard', dashboardId: 'bank_recon', title: 'Rapprochement banque ↔ GL' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '7. Lettrage tiers', inToc: true },
      { id: uid(), type: 'dashboard', dashboardId: 'lettrage', title: 'Taux de lettrage et vieillissement' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '8. Bilan & CR de la période', inToc: true },
      { id: uid(), type: 'table', source: 'bilan_actif', title: 'Bilan — Actif' },
      { id: uid(), type: 'table', source: 'bilan_passif', title: 'Bilan — Passif' },
      { id: uid(), type: 'table', source: 'cr', title: 'Compte de résultat' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '9. Anomalies à traiter avant validation', inToc: true },
      { id: uid(), type: 'dashboard', dashboardId: 'anomalies', title: 'Carte des anomalies' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '10. Checklist de clôture', inToc: true },
      { id: uid(), type: 'paragraph', text: "À compléter : items de la checklist." },
    ];
  },

  cash: (data) => {
    const k = computeKPIs(data);
    return [
      { id: uid(), type: 'h1', text: '1. Position de trésorerie', inToc: true },
      { id: uid(), type: 'paragraph', text: "Tableau de bord trésorerie complet : position actuelle, flux, prévisions, optimisation du cash." },
      { id: uid(), type: 'kpi', items: [
        { label: 'Trésorerie nette', value: k.treso }, { label: 'BFR', value: k.bfr },
        { label: 'DSO', value: k.dso, subValue: 'Délai clients' }, { label: "EBE", value: k.ebe },
      ]},
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '2. Évolution trésorerie', inToc: true },
      { id: uid(), type: 'dashboard', dashboardId: 'tre', title: 'Trésorerie — position et volatilité' },
      { id: uid(), type: 'dashboard', dashboardId: 'cashflow', title: 'Cashflow Statement' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '3. Cashflow prévisionnel 13 semaines', inToc: true },
      { id: uid(), type: 'dashboard', dashboardId: 'cashforecast', title: 'Projection 13 semaines + alertes' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '4. Rolling Forecast 90 jours', inToc: true },
      { id: uid(), type: 'dashboard', dashboardId: 'forecast', title: 'Forecast 30/60/90j' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '5. Working Capital Days', inToc: true },
      { id: uid(), type: 'dashboard', dashboardId: 'wcd', title: 'DSO / DIO / DPO / CCC' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '6. BFR — Décomposition', inToc: true },
      { id: uid(), type: 'dashboard', dashboardId: 'bfr', title: 'FR / BFR / TN' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '7. Cycle clients (recouvrement)', inToc: true },
      { id: uid(), type: 'dashboard', dashboardId: 'client', title: 'DSO + balance âgée + concentration' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '8. Cycle fournisseurs', inToc: true },
      { id: uid(), type: 'dashboard', dashboardId: 'fr', title: 'DPO + échéancier + dépendance' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '9. Saisonnalité', inToc: true },
      { id: uid(), type: 'dashboard', dashboardId: 'seasonality', title: 'Saisonnalité du CA (base 100)' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '10. Tableau de Flux de Trésorerie (TFT)', inToc: true },
      { id: uid(), type: 'table', source: 'tft', title: 'TFT — méthode indirecte' },
      { id: uid(), type: 'pageBreak' },
      { id: uid(), type: 'h1', text: '11. Plan d\'optimisation cash', inToc: true },
      { id: uid(), type: 'paragraph', text: "À compléter : actions sur DSO (relances), DIO (rotation stocks), DPO (négociation délais), gestion des excédents." },
    ];
  },

  // ─── Liasse IFRS — structure inspirée des « GT Example Financial Statements » :
  // intro/base de préparation → 5 états primaires → réconciliation IFRS 1 → notes.
  ifrs: () => [
    { id: uid(), type: 'h1', text: '1. Introduction et base de préparation', inToc: true },
    { id: uid(), type: 'paragraph', text: "Les présents états financiers sont convertis de la comptabilité SYSCOHADA révisé (AUDCIF 2017) vers un référentiel IFRS : reclassement de présentation (IAS 1 — distinction courant / non courant, suppression des éléments HAO) et retraitements de fond (IAS 38, IAS 21, IAS 20, IAS 12, et le cas échéant IFRS 16, IAS 19, IFRS 9). Les montants sont exprimés dans la devise de tenue de comptabilité. Les références normatives figurent en marge de chaque état." },
    { id: uid(), type: 'pageBreak' },
    { id: uid(), type: 'h1', text: '2. Compte de résultat (Statement of Profit or Loss)', inToc: true },
    { id: uid(), type: 'table', source: 'ifrs_pnl', title: 'Compte de résultat IFRS — par nature (IAS 1)' },
    { id: uid(), type: 'h2', text: '2.1 Résultat global (Other Comprehensive Income)', inToc: true },
    { id: uid(), type: 'table', source: 'ifrs_oci', title: 'État du résultat global (IAS 1.82A)' },
    { id: uid(), type: 'pageBreak' },
    { id: uid(), type: 'h1', text: '3. État de la situation financière (Statement of Financial Position)', inToc: true },
    { id: uid(), type: 'table', source: 'ifrs_sofp', title: 'Situation financière — current / non-current (IAS 1)' },
    { id: uid(), type: 'pageBreak' },
    { id: uid(), type: 'h1', text: '4. Variation des capitaux propres (Statement of Changes in Equity)', inToc: true },
    { id: uid(), type: 'table', source: 'ifrs_sce', title: 'Variation des capitaux propres (IAS 1.106)' },
    { id: uid(), type: 'pageBreak' },
    { id: uid(), type: 'h1', text: '5. Tableau des flux de trésorerie (Statement of Cash Flows)', inToc: true },
    { id: uid(), type: 'table', source: 'ifrs_cashflow', title: 'Flux de trésorerie — méthode indirecte (IAS 7)' },
    { id: uid(), type: 'pageBreak' },
    { id: uid(), type: 'h1', text: '6. Réconciliation SYSCOHADA → IFRS', inToc: true },
    { id: uid(), type: 'paragraph', text: "Ponts de réconciliation type IFRS 1 : passage des capitaux propres et du résultat SYSCOHADA aux montants IFRS, retraitement par retraitement." },
    { id: uid(), type: 'table', source: 'ifrs_recon', title: 'Ponts de réconciliation (IFRS 1)' },
    { id: uid(), type: 'pageBreak' },
    { id: uid(), type: 'h1', text: '7. Notes aux états financiers', inToc: true },
    { id: uid(), type: 'h2', text: '7.1 Principales méthodes comptables', inToc: true },
    { id: uid(), type: 'paragraph', text: "Immobilisations au coût amorti (IAS 16 / IAS 38) ; contrats de location capitalisés en droit d'usage et dette (IFRS 16) ; instruments financiers évalués selon IFRS 9 (dépréciation en pertes attendues) ; impôts différés sur différences temporelles (IAS 12) ; avantages du personnel selon IAS 19." },
    { id: uid(), type: 'h2', text: '7.2 Jugements et estimations', inToc: true },
    { id: uid(), type: 'paragraph', text: "À compléter : principales sources d'incertitude d'estimation (IAS 1.125) — durées d'utilité, taux d'actualisation, pertes attendues sur créances, hypothèses actuarielles." },
    { id: uid(), type: 'h2', text: '7.3 Événements postérieurs à la clôture', inToc: true },
    { id: uid(), type: 'paragraph', text: "À compléter : événements significatifs postérieurs à la date de clôture (IAS 10) et date d'autorisation de publication des états financiers (IAS 1.138)." },
    { id: uid(), type: 'h2', text: '7.4 Portée de la conversion', inToc: true },
    { id: uid(), type: 'paragraph', text: "Conversion indicative de gestion. Pour un reporting IFRS audité, faire valider les retraitements et compléter les postes hors périmètre (information sectorielle IFRS 8, instruments financiers IFRS 7/9 détaillés, notes complètes) par un cabinet." },
  ],
};
